BEGIN {
	n = 0;
	print "/* AUTOGENERATED by gen_prims_c.awk */"
	print "#include \"mlvalues.h\"";
	print "#include \"prims.h\"";
};

/^\#.*$/ { }

/^[A-Za-z].*$/ {
	defs[n] = $0; n++;
};

END {
	for (x = 0; x < n; x++)
		printf "extern value %s();\n", defs[x];
	printf("c_primitive cprim[] = {\n");
	for (x = 0; x < n; x++) {
		printf "  %s,\n", defs[x];
	}

	printf("  0};\n");
	printf("char *names_of_cprim[] = {\n");
	for (x = 0; x < n; x++)
		printf "  \"%s\",\n", defs[x];
        printf("  0};\n");
}
