BEGIN {
	n = 0;
	print "/* AUTOGENERATED by gen_instruct_h.awk */;
	print "enum instructions {";
};

/^#.*$/ {}

// {
	defs[n] = $0; n++;
};

END {
	for (x = 1; x < n; x++)
		printf "  %s,\n", defs[x];
	printf("  };\n");

	printf("char * names_of_instructions [] = {\n");
	for (x = 1; x < n; x++)
		printf "  \"%s\",\n", defs[x];
	printf("  };\n");
}
