# -*- mode: awk
# This program generates the global table for the C runtime from the globals.def
# global definition file.

# Set up a mention that the file is autogenerated
BEGIN {
	n = 0;
	print "/* AUTOGENERATED by gen_global_table_h.awk */";
	print "#ifndef _GLOBAL_TBL_H";
	print "#define _GLOBAL_TBL_H";
	print "#include \"mlvalues.h\"";
	print "extern value global_data;";
};

# Strip out comments
/^#.*$/ {}

# Globals are handled by producing the corresponding global definition in the
# header file
/^global .*$/ {
	print "#define", $2, $3;
}

# Exceptions are also defines in the C runtime
/^exn .*$/ {
        print "#define", $2, $3;
}

/^exn_val .*$/ {
        print "#define", $2, $3;
}

/^first_exception .*$/ {
	print "#define SYS__FIRST_EXN", $2;
}

/^last_exception .*$/ {
	print "#define SYS__LAST_EXN", $2;
}
END {
	print "#endif";
}
