BEGIN {
	n = 0;
	print "/* AUTOGENERATED by gen_instruct_c.awk */";
};

/^#.*$/ {}

/^[A-Za-z].*$/ {
	defs[n] = $0; n++;
};

END {
	printf("char * names_of_instructions [] = {\n");
	for (x = 0; x < n; x++)
		printf "  \"%s\",\n", defs[x];
	printf("  };\n");
}
