BEGIN {
	n = 0;
	print "/* AUTOGENERATED by gen_instruct_h.awk */";
	print "extern char *names_of_instructions[];"
	print "enum instructions {";
};

/^#.*$/ {}

/^[A-Za-z].*$/ {
	defs[n] = $0; n++;
};

END {
	for (x = 0; x < n; x++)
		printf "  %s,\n", defs[x];
	printf("  };\n");
}
