#!/bin/sh
# -*- sh -*-

program=$1
ok_output=${2-$1.ok}
errok_output=${3-'tests/empty.errok'}

if test -z "$srcdir"; then
    srcdir=$(echo "$0" | sed 's,[^/]*$,,')
    test "$srcdir" = "$0" && srcdir=.
    test -z "$srcdir" && srcdir=.
    test "${VERBOSE+set}" != set && VERBOSE=1
fi

. $srcdir/defs

# Run test
${MOSMLC} ${srcdir}/${program}
${MOSMLLNK} -exec a.out ${srcdir}/${program}
${CAMLRUNM} a.out 2>&1 | tee -i out

if ${CMP} -s out ${srcdir}/${ok_output}; then
    :
else
    echo "ok: " >&2
    cat ${srcdir}/${ok_output} >&2
    exit 1
fi

# Munge error output to remove leading directories, `lt-' or
# trailing `.exe'
#sed -e "s,^[^:]*[lt-]*sic[.ex]*:,sic:," err >sederr && mv sederr err

# Show stderr if doesnt match expected output if VERBOSE == 1
#if "$CMP" -s err ${srcdir}/${errok_output}; then
#    :
#else
#    echo "err:" >&2
#    cat err >&2
#    echo "errok:" >&2
#    cat ${srcdir}/${errok_output} >&2
#    exit 1
#fi
