# -*- mode: awk-mode
# This program generates the global table for the C runtime from the globals.def
# global definition file.

# Set up a mention that the file is autogenerated
BEGIN {
	n = 0;
	print "(* AUTOGENERATED by gen_predef_sml.awk *)";
	print "local open Const in";
	print "val predef_variables = [";
};

# Strip out comments
/^#.*$/ {}

# Globals are handled by producing the corresponding global definition in the
# header file
/^global .*$/ {
	defs[n] = $5;
	n++;
}

# Exceptions are also defines in the C runtime
/^exn .*$/ {
	defs[n] = $5;
	n++;
}

/^exn_val .*$/ {
	defs[n] = $5;
	n++;
}

END {
	for (x = 0; x < n-1; x++) {
		print "  {qual=\"General\", id=\"" defs[x] "\"},";
	}
	print "  {qual=\"General\", id=\"" defs[n-1] "\"}]";
	print "end"
}
